__global_conditions:
  expected_modules:
    - varbase_editor
editor.editor.full_html:
  expected_config:
    settings:
      toolbar:
        rows:
          0:
            0:
              name: 'Block Formatting'
              items:
                - Cut
                - Copy
                - Paste
                - PasteFromWord
                - '-'
                - Undo
                - Redo
            1:
              name: Media
              items:
                - media
                - Embed
                - '-'
                - Blockquote
                - HorizontalRule
                - '-'
                - Table
            2:
              name: Linking
              items:
                - '-'
                - Linkit
                - '-'
                - Link
                - Unlink
                - '-'
                - Anchor
            3:
              name: Tools
              items:
                - ShowBlocks
                - Maximize
                - Source
          1:
            0:
              name: Style
              items:
                - Styles
                - Format
            1:
              name: Formatting
              items:
                - Bold
                - Italic
                - Underline
                - Strike
                - '-'
                - Subscript
                - Superscript
                - '-'
                - RemoveFormat
            2:
              name: Lists
              items:
                - NumberedList
                - BulletedList
                - '-'
                - Outdent
                - Indent
            3:
              name: Alignment
              items:
                - JustifyLeft
                - JustifyCenter
                - JustifyRight
                - '-'
                - BidiLtr
                - BidiRtl
                - '-'
                - Language
  update_actions:
    delete:
      settings:
        toolbar:
          rows:
            0:
              0:
                name: 'Block Formatting'
                items:
                  - Cut
                  - Copy
                  - Paste
                  - PasteFromWord
                  - '-'
                  - Undo
                  - Redo
              1:
                name: Media
                items:
                  - media
                  - Embed
                  - '-'
                  - Blockquote
                  - HorizontalRule
                  - '-'
                  - Table
              2:
                name: Linking
                items:
                  - '-'
                  - Linkit
                  - '-'
                  - Link
                  - Unlink
                  - '-'
                  - Anchor
              3:
                name: Tools
                items:
                  - ShowBlocks
                  - Maximize
                  - Source
            1:
              0:
                name: Style
                items:
                  - Styles
                  - Format
              1:
                name: Formatting
                items:
                  - Bold
                  - Italic
                  - Underline
                  - Strike
                  - '-'
                  - Subscript
                  - Superscript
                  - '-'
                  - RemoveFormat
              2:
                name: Lists
                items:
                  - NumberedList
                  - BulletedList
                  - '-'
                  - Outdent
                  - Indent
              3:
                name: Alignment
                items:
                  - JustifyLeft
                  - JustifyCenter
                  - JustifyRight
                  - '-'
                  - BidiLtr
                  - BidiRtl
                  - '-'
                  - Language
    add:
      settings:
        toolbar:
          rows:
            0:
              0:
                name: 'Block Formatting'
                items:
                  - Cut
                  - Copy
                  - Paste
                  - PasteFromWord
                  - '-'
                  - Undo
                  - Redo
              1:
                name: Media
                items:
                  - media
                  - Embed
                  - '-'
                  - Blockquote
                  - HorizontalRule
                  - '-'
                  - Table
              2:
                name: Linking
                items:
                  - '-'
                  - Linkit
                  - '-'
                  - Link
                  - Unlink
                  - '-'
                  - Anchor
              3:
                name: Tools
                items:
                  - ShowBlocks
                  - Maximize
                  - Source
            1:
              0:
                name: Style
                items:
                  - Styles
                  - Format
              1:
                name: Formatting
                items:
                  - Bold
                  - Italic
                  - Underline
                  - Strike
                  - '-'
                  - Subscript
                  - Superscript
                  - '-'
                  - RemoveFormat
              2:
                name: Lists
                items:
                  - NumberedList
                  - BulletedList
                  - '-'
                  - Outdent
                  - Indent
              3:
                name: Alignment
                items:
                  - JustifyLeft
                  - JustifyCenter
                  - JustifyRight
                  - '-'
                  - BidiLtr
                  - BidiRtl
                  - '-'
filter.format.basic_html:
  expected_config:
    filters:
      ace_filter:
        settings:
          auto_complete: true
        weight: 0
      editor_file_reference:
        weight: -45
      entity_embed:
        status: false
        weight: -43
      filter_autop:
        weight: -42
      filter_html:
        settings:
          allowed_html: '<a href hreflang !href accesskey id rel target title> <blockquote cite> <br> <cite> <code> <dd> <dl> <dt> <em> <h2 id> <h3 id> <h4 id> <h5 id> <h6 id> <li> <ol start type> <p> <span> <strong> <u> <ul type> <img src alt height width data-* data-entity-type data-entity-uuid data-align data-caption> <drupal-entity data-entity-type data-entity-uuid data-entity-embed-display data-entity-embed-display-settings data-align data-caption data-embed-button>'
      filter_html_escape:
        weight: -44
      filter_image_resize:
        weight: 0
  update_actions:
    add:
      filters:
        filter_ckeditor_media_embed:
          id: filter_ckeditor_media_embed
          provider: ckeditor_media_embed
          settings: {  }
          status: false
          weight: -37
        filter_image_link_to_source:
          id: filter_image_link_to_source
          provider: image_resize_filter
          settings: {  }
          status: false
          weight: -36
    change:
      filters:
        ace_filter:
          weight: -38
        blazy_filter:
          id: blazy_filter
          provider: blazy
          settings:
            filter_tags:
              iframe: iframe
              img: img
            media_switch: ''
            use_data_uri: '0'
          status: false
          weight: -35
        editor_file_reference:
          weight: -44
        entity_embed:
          status: true
          weight: -45
        filter_autop:
          weight: -41
        filter_html:
          settings:
            allowed_html: '<a href hreflang !href accesskey id rel target title> <blockquote cite> <br> <cite> <code> <dd> <dl> <dt> <em> <h2 id> <h3 id> <h4 id> <h5 id> <h6 id> <li> <ol start type> <p> <span> <strong> <u> <ul type> <img src alt height width data-* data-entity-type data-entity-uuid data-align data-caption> <drupal-entity data-entity-type data-entity-uuid data-entity-embed-display data-entity-embed-display-settings data-align data-caption data-embed-button data-langcode alt title>'
        filter_html_escape:
          weight: -42
        filter_image_resize:
          weight: -43
    delete:
      filters:
        ace_filter:
          settings:
            auto_complete: true
filter.format.full_html:
  expected_config:
    filters:
      ace_filter:
        settings:
          auto_complete: true
        weight: -36
      editor_file_reference:
        weight: -41
      entity_embed:
        weight: -49
      filter_align:
        weight: -48
      filter_autop:
        weight: -38
      filter_caption:
        weight: -47
      filter_ckeditor_media_embed:
        weight: -44
      filter_html:
        weight: -50
      filter_html_escape:
        weight: -39
      filter_html_image_secure:
        weight: -37
      filter_htmlcorrector:
        weight: -42
      filter_image_link_to_source:
        weight: -35
      filter_image_resize:
        weight: -40
      filter_pathologic:
        weight: -45
      filter_url:
        weight: -43
  update_actions:
    change:
      filters:
        ace_filter:
          weight: -37
        blazy_filter:
          id: blazy_filter
          provider: blazy
          settings:
            filter_tags:
              iframe: iframe
              img: img
            media_switch: ''
            use_data_uri: '0'
          status: false
          weight: -35
        editor_file_reference:
          weight: -43
        entity_embed:
          weight: -48
        filter_align:
          weight: -50
        filter_autop:
          weight: -39
        filter_caption:
          weight: -49
        filter_ckeditor_media_embed:
          weight: -46
        filter_html:
          weight: -41
        filter_html_escape:
          weight: -40
        filter_html_image_secure:
          weight: -38
        filter_htmlcorrector:
          weight: -44
        filter_image_link_to_source:
          weight: -36
        filter_image_resize:
          weight: -42
        filter_pathologic:
          weight: -47
        filter_url:
          weight: -45
    delete:
      filters:
        ace_filter:
          settings:
            auto_complete: true
