core.entity_form_display.node.page.default:
  expected_config:
    content:
      langcode:
        settings: {  }
      title:
        third_party_settings: {  }
  update_actions:
    add:
      content:
        url_redirects:
          settings: {  }
          third_party_settings: {  }
    change:
      content:
        langcode:
          settings:
            include_locked: true
        title:
          third_party_settings:
            advanced_text_formatter:
              show_token_tree: 0
            length_indicator:
              indicator: true
              indicator_opt:
                optimax: 50
                optimin: 15
                tolerance: 10
            maxlength:
              maxlength_js: null
              maxlength_js_label: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
